---
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.package:
        name:
          - wrk
        state: present

# 1 replica
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service for 1
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 1 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking for 1
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_for_1

    - name: Debug output for 1
      ansible.builtin.debug:
        msg: '{{ wrk_output_for_1.stdout_lines | select("search", "Req/Sec") | list }}'

# 2 replicas
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service for 2
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 2 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking for 2
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_for_2

    - name: Debug output for 2 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_for_2.stdout_lines | select("search", "Req/Sec") | list }}'

# 4 replicas
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True
    - name: create whoami service for 4
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 4 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking for 4
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_for_4

    - name: Debug output for 4 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_for_4.stdout_lines | select("search", "Req/Sec") | list }}'

# 8 replicas
- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True
    - name: create whoami service for 8
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 8 containous/whoami"
      become: yes

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Benchmarking for 8
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output_for_8

    - name: Debug output for 8 replicas
      ansible.builtin.debug:
        msg: '{{ wrk_output_for_8.stdout_lines | select("search", "Req/Sec") | list }}'